version: '3'

services:
  db:
    container_name: 'edi-db'
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edi_labs
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
